permalink:    /:year/:month/:day/:title
analytics_id: UA-19957147-1
title:        Joway.W
description:  Personal website of Dave Lim
url:          http://dlimiter.net
#url:          http://0.0.0.0:4000
author:       Joway.W
email:        670425438@qq.com
twitter:      http://twitter.com/joway_w
github:       http://github.com/joway
dribbble:     http://dribbble.com/dlimiter
linkedin:     http://au.linkedin.com/in/dlimiter
zerply:       http://zerply.com/profile/dlimiter/public
keywords:     design,development,software,illustration,css,html,ruby,rails,blog
comments:     true
feed:         http://feeds.feedburner.com/dlimiterdotnet
ignore:       _blog, _posts/folio
exclude:      Gemfile, Gemfile.lock, Rakefile