# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Joway.W
tagline:
description:
url:              http://Joway-W.com

author:
  name:           'Joway.W'
  url:            https://twitter.com/joway_w

paginate:         2

# Custom vars

github:
  repo:          https://github.com/joway
